services:
  db:
    container_name: pg_db
    image: postgres:14-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
    networks:
      net1:
        ipv4_address: 172.20.0.2
        
  django_gunicorn:
    depends_on:
      - db
    container_name: slovo
    image: slovo:latest
    volumes:
      - logs_webapp:/app/logs
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      net1:
        ipv4_address: 172.20.0.3

volumes:
  logs_webapp:
    name: "slovo_logs"
  postgres-data:
    name: "pg_db"

networks:
  net1:
    name: net1
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
