services:
  db:
    image: postgres:14-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  static: